[project]
name = "olysched"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pytz",
    "python-dateutil",
    "requests",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
